# Generated by Django 2.0.8 on 2018-09-16 23:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=200)),
                ('email_id', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=10)),
                ('city', models.TextField()),
                ('state', models.TextField()),
                ('country', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='OrderedProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=10)),
                ('brand', models.CharField(max_length=200)),
                ('purchase_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('sell_date', models.DateTimeField(default='')),
                ('dealer', models.CharField(max_length=200)),
                ('product_image', models.FileField(default='', upload_to='')),
                ('expiry_date', models.DateTimeField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='SoldProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default='')),
            ],
        ),
    ]
